name: build

on: [push, pull_request]

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android
        run: ./gradlew assembleDebug
        working-directory: android

      - name: Extract branch name
        shell: bash
        id: extract_branch
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '_')" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: mv android/app/build/outputs/apk/debug/app-debug.apk android/app/build/outputs/apk/debug/Axion-android.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Axion-${{ steps.extract_branch.outputs.branch }}-android
          path: android/app/build/outputs/apk/debug/Axion-android.apk
